name: 'Setup Goose CLI'
description: 'Install and cache Goose AI agent for GitHub Actions workflows'
author: 'Hugues Clouâtre'

keywords:
  - ai
  - ai-agent
  - goose
  - automation
  - cli

inputs:
  version:
    description: 'Goose version to install (e.g., 1.14.0)'
    required: false
    default: '1.19.1'

outputs:
  goose-version:
    description: 'Installed Goose version'
    value: ${{ inputs.version }}
  goose-path:
    description: 'Path to Goose binary directory'
    value: ${{ steps.setup-path.outputs.path }}
  cache-hit:
    description: 'Whether the Goose binary was restored from cache'
    value: ${{ steps.cache-goose.outputs.cache-hit }}

runs:
  using: 'composite'
  steps:
    - name: Check platform
      shell: bash
      run: |
        if [ "${{ runner.os }}" != "Linux" ]; then
          echo "::error::This action only supports Linux runners. Current OS: ${{ runner.os }}"
          exit 1
        fi

    - name: Cache Goose binary
      id: cache-goose
      uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5
      with:
        path: ~/.local/bin/goose
        key: goose-${{ inputs.version }}-${{ runner.os }}-${{ runner.arch }}
        restore-keys: |
          goose-${{ inputs.version }}-${{ runner.os }}-

    - name: Install Goose
      id: install
      if: steps.cache-goose.outputs.cache-hit != 'true'
      shell: bash
      run: |
        echo "::group::Installing Goose v${{ inputs.version }}"
        mkdir -p ~/.local/bin
        
        # Determine architecture
        ARCH="${{ runner.arch }}"
        if [ "$ARCH" = "X64" ]; then
          GOOSE_ARCH="x86_64"
        elif [ "$ARCH" = "ARM64" ]; then
          GOOSE_ARCH="aarch64"
        else
          echo "::error::Unsupported architecture: $ARCH"
          exit 1
        fi
        
        # Download and extract
        DOWNLOAD_URL="https://github.com/block/goose/releases/download/v${{ inputs.version }}/goose-${GOOSE_ARCH}-unknown-linux-gnu.tar.bz2"
        echo "Downloading from: $DOWNLOAD_URL"
        
        curl -fsSL "$DOWNLOAD_URL" | tar -xj -C ~/.local/bin
        chmod +x ~/.local/bin/goose
        
        echo "::endgroup::"

    - name: Setup PATH
      id: setup-path
      shell: bash
      run: |
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        echo "path=$HOME/.local/bin" >> $GITHUB_OUTPUT

    - name: Verify installation
      shell: bash
      run: |
        echo "::group::Verifying Goose installation"
        goose --version
        echo "Installed binary:"
        ls -lh ~/.local/bin/goose
        echo "::endgroup::"

branding:
  icon: 'zap'
  color: 'purple'
