# Example: Auto-generate Documentation
# Keep docs in sync with code changes

name: Update Documentation

on:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - 'lib/**'

permissions:
  contents: write

jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: clouatre-labs/setup-goose-action@v1
      
      - name: Generate API documentation
        env:
          GOOGLE_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          goose session --profile ci <<EOF
          Update API.md documentation based on current code in src/
          
          Include:
          - Function signatures
          - Parameters and return types
          - Usage examples
          - Recent changes
          EOF
      
      - name: Commit updated docs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/
          git diff --staged --quiet || git commit -m "docs: update API documentation"
          git push
