# Example: AI-Powered Pull Request Review
# Automatically review PRs for logic issues, bugs, and improvements

name: AI Code Review

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - '**.py'
      - '**.js'
      - '**.ts'
      - '**.go'
      - '**.rs'

permissions:
  contents: read
  pull-requests: write

jobs:
  ai-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - uses: clouatre-labs/setup-goose-action@v1
      
      - name: Get changed files
        id: changes
        run: |
          echo "files<<EOF" >> $GITHUB_OUTPUT
          git diff --name-only origin/${{ github.base_ref }}...HEAD >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      
      - name: AI Review with Goose
        env:
          GOOGLE_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          goose session --profile ci <<EOF
          Review the following changed files for:
          - Logic errors
          - Security vulnerabilities
          - Performance issues
          - Code quality improvements
          
          Files:
          ${{ steps.changes.outputs.files }}
          
          Provide concise, actionable feedback.
          EOF
